// Generated by ReScript, PLEASE EDIT WITH CARE


function make(title) {
  var n = new Notification(title);
  n.onclick = (function (param) {
      window.focus();
    });
}

export {
  make ,
}
/* No side effect */
