// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";

var ServiceWorkerRegistration = {};

function make(title) {
  Js_promise2.then(navigator.serviceWorker.ready, (function (registration) {
          return registration.showNotification(title);
        }));
}

export {
  ServiceWorkerRegistration ,
  make ,
}
/* No side effect */
